
device_id: 1  # Try different camera indices
fps: 30       # Adjust based on camera capability
plugins:
  - name: black_screen
    module: plugins.black_screen_detector
    class: BlackScreenDetector
    status: "enable"
    config:
      variance_threshold: 50
      histogram_threshold: 0.8
      result_holding_frames: 5

  - name: artifact_detector
    module: plugins.artifact_detector
    class: ArtifactDetector
    status: "enable"
    config:
      black_threshold: 20    # 黑屏检测阈值
      blur_threshold: 80     # 模糊检测阈值  
      noise_threshold: 25    # 噪声检测阈值
      detection_interval: 15 # 检测间隔帧数
      alarm_duration: 10     # 告警持续帧数
      ssim_threshold: 0.85
      result_holding_frames: 5

  - name: pattern_noise
    module: plugins.pattern_noise_detector
    class: PatternNoiseDetector
    status: "enable"
    config:
      pattern_threshold: 0.5  # 花屏模式得分阈值
      variance_threshold: 50  # 图像方差阈值
      history_size: 5         # 帧历史记录大小
      edge_pixels: 5000
      result_holding_frames: 5

  - name: signature
    module: plugins.signature_plugin
    class: VideoSignaturePlugin
    #status: "enable"
    config:
      operations: "generate" # operation ('generate', 'compare')
      directory: "./fingerprints" # fingerprints direcory to compare with not used in generate mode
      duration: 100 # number of frames to check
      method: "combined" #Signature method ('phash', 'dhash', 'histogram', 'combined')
      threshold: 0.85
      phash_weight: 0.35
      dhash_weight: 0.25
      histogram_weight: 0.2
      edge_ratio_weight: 0.1
      gradient_hist_weight: 0.1