
case_config:
  device_id: 0  # Try different camera indices
  rex_x: 1280   # x reslution
  res_y: 720    # y resolution
  fps: 30       # analysis frame pre-second
  run_time: 20  # Run for 20 seconds
tests:
  timeout: 30   # second wait for prompt string
  prompt: "screen starts" # prompt to show the test start
  expect: ["sample.display.shield"]
plugins:
  - name: black_screen
    module: .plugins.black_screen_detector
    class: BlackScreenDetector
    #status: "enable"
    config:
      variance_threshold: 50
      histogram_threshold: 0.8
      result_holding_frames: 5

  - name: artifact_detector
    module: .plugins.artifact_detector
    class: ArtifactDetector
    #status: "enable"
    config:
      black_threshold: 20    # Black screen detection threshold
      blur_threshold: 80     # Blur detection threshold  
      noise_threshold: 25    # Noise detection threshold
      detection_interval: 15 # Detection interval in frames
      alarm_duration: 10     # Alarm duration in frames
      ssim_threshold: 0.85
      result_holding_frames: 5

  - name: pattern_noise
    module: .plugins.pattern_noise_detector
    class: PatternNoiseDetector
    #status: "enable"
    config:
      pattern_threshold: 0.5  # Pattern noise score threshold
      variance_threshold: 50  # Image variance threshold
      history_size: 5         # Frame history size
      edge_pixels: 5000
      result_holding_frames: 5

  - name: signature
    module: .plugins.signature_plugin
    class: VideoSignaturePlugin
    status: "enable"
    config:
      operations: "compare" # operation ('generate', 'compare')
      metadata:
        name: "test.display.shield" # finger-print stored metadata
        platform: "frdm_mcxn947"
      directory: "./camera_shield/fingerprints" # fingerprints directory to compare with not used in generate mode
      duration: 100 # number of frames to check
      method: "combined" #Signature method ('phash', 'dhash', 'histogram', 'combined')
      threshold: 0.65
      phash_weight: 0.35
      dhash_weight: 0.25
      histogram_weight: 0.2
      edge_ratio_weight: 0.1
      gradient_hist_weight: 0.1
